trigger: none

pool:
  vmImage: 'ubuntu-latest'

container: 'rocker/tidyverse:latest'

steps:

  - script: sudo Rscript -e 'devtools::check(cran = FALSE)'
displayName: 'Package Check'
continueOnError: true

- script: Rscript -e 'sessionInfo()'
displayName: 'R Version'
